# Generated by Django 5.2 on 2026-01-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(height_field='picture_height', upload_to='product_images/', width_field='picture_width'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(height_field='picture_height', upload_to='product_images/', width_field='picture_width'),
        ),
    ]
