# Generated by Django 5.2 on 2026-01-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='URL of the product image.', upload_to=''),
        ),
    ]
