# Generated by Django 5.2 on 2026-01-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='amazon_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
