# Generated by Django 5.2 on 2026-01-18 16:21

import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_categoryimage_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['AVIF'], grid_columns=12, height_field='picture_height', pixel_densities=[1, 2], upload_to='category_image/', width_field='picture_width'),
        ),
    ]
