# Generated by Django 5.2 on 2026-01-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_category_amazon_id_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='asin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='File for the product image.', upload_to=''),
        ),
    ]
