# Generated by Django 5.2 on 2026-01-12 17:19

import pictures.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_asin_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['AVIF'], grid_columns=12, pixel_densities=[1, 2], upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['AVIF'], grid_columns=12, help_text='File for the product image.', pixel_densities=[1, 2], upload_to='product_images/'),
        ),
    ]
